{{- $dot := . }}
{{- range $service := (list "frontend" "history" "matching" "worker") }}
{{- $serviceCfg := index $.Values $service -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence-{{ $service }}
  labels:
    app: cadence
    component: {{ $service }}
    {{- include "cadence.commonlabels" $dot | nindent 4 }}
spec:
  replicas: {{ $serviceCfg.replicas }}
  selector:
    matchLabels:
      app: cadence
      component: {{ $service }}
  template:
    metadata:
      labels:
        app: cadence
        component: {{ $service }}
    spec:
      initContainers:
        - name: check-postgres-service
          image: busybox
          command:
            - sh
            - '-c'
            - >-
              until nslookup $DB_HOST; do echo waiting for postgres service; sleep 1; done;
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rds-config
                  key: db_host
      containers:
        - name: cadence-{{ $service }}
          image: {{ $serviceCfg.image.repository }}:{{ $serviceCfg.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: rpc
              containerPort: {{ $serviceCfg.port }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            {{- if ne $service "worker" }}
            - name: grpc
              containerPort: {{ $serviceCfg.grpcPort }}
              protocol: TCP
            {{- end}}
          env:
            - name: SERVICES
              value: {{ $service }}
            - name: BIND_ON_IP
              value: 0.0.0.0
            - name: BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DB
              value: "postgres"
            - name: POSTGRESQL_SEEDS
              value: {{ $.Values.postgresql.endpoint }}
            - name: POSTGRESQL_USER
              value: {{ $.Values.postgresql.user }}
            - name: POSTGRESQL_PASSWORD
              value: {{ $.Values.postgresql.password }}
            - name: POSTGRESQL_DATABASE
              value: {{ $.Values.postgresql.database }}
            - name: POSTGRESQL_VISIBILITY_DATABASE
              value: {{ $.Values.postgresql.visibility_database }}
            - name: PROMETHEUS_ENDPOINT
              value: :9090
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/development.yaml
            - name: PRIMARY_FRONTEND_SERVICE
              value: cadence-frontend.{{ $.Release.Namespace }}.svc.cluster.local
            - name: LOG_LEVEL
              value: {{ $.Values.log.level }}
            - name: LOG_STDOUT
              value: {{ $.Values.log.stdout | quote }}
            - name: ENABLE_ES
              value: "false"
            - name: SKIP_SCHEMA_SETUP
              value: "true"
            - name: RINGPOP_BOOTSTRAP_MODE
              value: dns
            - name: RINGPOP_SEEDS
              value: cadence-frontend-headless.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.frontend.port }},cadence-history-headless.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.history.port }},cadence-matching-headless.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.matching.port }},cadence-worker-headless.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.worker.port }}

          resources:
            limits:
              cpu: {{ $serviceCfg.cpu.limit }}
              memory: {{ $serviceCfg.memory.limit }}
            requests:
              cpu: {{ $serviceCfg.cpu.request }}
              memory: {{ $serviceCfg.memory.request }}
      volumes:
        - name: config
          configMap:
            name: cadence-configmap
---
{{- end }}